### PR TITLE
Added debugging to stderr, fixed working directory and removed a lot of notices

### PR DESCRIPTION
**Pull request by bwoebi**
style.css always returned a 500 because of the notices (I have them enabled in my php.ini).

also I used chdir() in MacOS/drag0n as I installed it in /Applications/drag0n/drag0n.app and then it broke...

The logger now redirects everything to stderr (or do you really want it on stdout…? ;-))

### CODE REVIEW

**Comment by IngwiePhoenix** [comment]
Totally going to apply the fix next! Yes...i dont want it in stdout ... makes no sense at all x)
Am 05.09.2013 um 01:17 schrieb Bob Weinand notifications@github.com:

> style.css always returned a 500 because of the notices (I have them enabled in my php.ini).
> 
> also I used chdir() in MacOS/drag0n as I installed it in /Applications/drag0n/drag0n.app and then it broke...
> 
> The logger now redirects everything to stderr (or do you really want it on stdout…? ;-))
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/bwoebi/drag0n master
> Or view, comment on, or merge it at:
> 
>   https://github.com/IngwiePhoenix/drag0n/pull/1
> 
> Commit Summary
> 
> Added debugging to stderr, fixed working directory and removed a lot of notices
> File Changes
> 
> M drag0n.app/Contents/Interface/css/component.css.php (8)
> M drag0n.app/Contents/Interface/css/default.css.php (112)
> M drag0n.app/Contents/Interface/css/drag0n.css.php (84)
> M drag0n.app/Contents/Interface/css/style.css (3)
> M drag0n.app/Contents/MacOS/d0GUI.php (4)
> M drag0n.app/Contents/MacOS/drag0n (12)
> Patch Links:
> 
> https://github.com/IngwiePhoenix/drag0n/pull/1.patch
> https://github.com/IngwiePhoenix/drag0n/pull/1.diff

**Comment by IngwiePhoenix** [comment]
I have changed a lot of files. Can you reproduce the fix you wrote? I will wait for it and then merge it~

**Comment by bwoebi** [comment]
Readded my changes… Is now working with your actual update.

**Comment by bwoebi** [comment]
Was war der letzte Commit eben? Der funktionnierte nicht richtig. Du solltest hier aus github heraus mergen?

**Comment by IngwiePhoenix** [comment]
Github meinte, das ich per cmd mergen soll...und da war alles OK. Wobei, n bissl merkwürdig.

Kevins-MacBook-Air:drag0n Ingwie$ git checkout -b bwoebi-master master
Switched to a new branch 'bwoebi-master'
Kevins-MacBook-Air:drag0n Ingwie$ git pull https://github.com/bwoebi/drag0n.git master
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 5), reused 7 (delta 1)
Unpacking objects: 100% (12/12), done.
From https://github.com/bwoebi/drag0n
- branch            master     -> FETCH_HEAD
  Auto-merging drag0n.app/Contents/MacOS/drag0n
  CONFLICT (content): Merge conflict in drag0n.app/Contents/MacOS/drag0n
  Automatic merge failed; fix conflicts and then commit the result.
  Kevins-MacBook-Air:drag0n Ingwie$ git checkout master
  drag0n.app/Contents/MacOS/drag0n: needs merge
  error: you need to resolve your current index first
  Kevins-MacBook-Air:drag0n Ingwie$ git merge bwoebi-master
  error: 'merge' is not possible because you have unmerged files.
  hint: Fix them up in the work tree,
  hint: and then use 'git add/rm <file>' as
  hint: appropriate to mark resolution and make a commit,
  hint: or use 'git commit -a'.
  fatal: Exiting because of an unresolved conflict.
  Kevins-MacBook-Air:drag0n Ingwie$ git commit -a
  [bwoebi-master 8061a84] Merge branch 'master' of https://github.com/bwoebi/drag0n into bwoebi-master
  Kevins-MacBook-Air:drag0n Ingwie$ git commit -a
  # On branch bwoebi-master
  nothing to commit (working directory clean)
  Kevins-MacBook-Air:drag0n Ingwie$ git checkout master
  Switched to branch 'master'
  Kevins-MacBook-Air:drag0n Ingwie$ git push origin master
  Everything up-to-date
  Kevins-MacBook-Air:drag0n Ingwie$ git commit
  # On branch master
  nothing to commit (working directory clean)
  Kevins-MacBook-Air:drag0n Ingwie$ ls
  ./           ../          .DS_Store    .git/        .gitignore   .gitmodules  drag0n.app/  readme.md
  Kevins-MacBook-Air:drag0n Ingwie$ cat .gitmodules 
  [submodule "drag0n.app/Contents/Library/WingStyle"]
  path = drag0n.app/Contents/Library/WingStyle
  url = https://github.com/IngwiePhoenix/drag0n.git

Schau mal ob da was falsch lief
Am 05.09.2013 um 22:40 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
Also, bitte, ich bin genau so wenig git Experte :o

```
CONFLICT (content): Merge conflict in drag0n.app/Contents/MacOS/drag0n
```

Bleib mal danach in deiner branch und öffne die Datei… dann nach der Bearbeitung `git add drag0n.app/Contents/MacOS/drag0n` und dann mergen.

**Comment by IngwiePhoenix** [comment]
Den Konflikt hab ich ja behoben und editiert. Dann wollt git das ich comitte, was ich ja auch gemacht hab. o.o... Ich git (anstatt von "get" x) ) ne kriese ^^;
Am 05.09.2013 um 22:59 schrieb Bob Weinand notifications@github.com:

**Comment by IngwiePhoenix** [comment]
Ah ja... Git hat meinen Change also gekillt? :D
Der fix is jetzt drinn...endlich... ^^;
Am 05.09.2013 um 22:59 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
Scheint so… hauptsache es funzt^^

**Comment by bwoebi** [comment]
Ach… Meinen Nicknamen schreiben üben wir nochmals xP

**Comment by bwoebi** [comment]
Du hast übrigens auch noch nicht alles gepatcht?

**Comment by IngwiePhoenix** [comment]
Die Konstanten die du mit Anführungszeichen versehen hast, sind auto-konstanten von WingStyle -  sprich, keine "" nötig :) Ansonnsten hab ich nichts gefunden was ich hätte nachtragen müssen? o.o
Am 05.09.2013 um 23:18 schrieb Bob Weinand notifications@github.com:

**Pull request merged**
